"""Initial Supabase migration

Revision ID: e841c193f31f
Revises: 
Create Date: 2025-11-10 17:08:31.924109

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e841c193f31f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('alias_name', sa.String(length=50), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('time', sa.Time(), nullable=True),
    sa.Column('logo_filename', sa.String(length=255), nullable=True),
    sa.Column('location', sa.String(length=300), nullable=True),
    sa.Column('google_maps_url', sa.String(length=500), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('certificate_type', sa.String(length=50), nullable=True),
    sa.Column('organizer_name', sa.String(length=200), nullable=True),
    sa.Column('organizer_logo_url', sa.String(length=500), nullable=True),
    sa.Column('sponsor_name', sa.String(length=200), nullable=True),
    sa.Column('sponsor_logo_url', sa.String(length=500), nullable=True),
    sa.Column('event_location_cert', sa.String(length=300), nullable=True),
    sa.Column('event_theme', sa.String(length=100), nullable=True),
    sa.Column('signature1_name', sa.String(length=100), nullable=True),
    sa.Column('signature1_title', sa.String(length=100), nullable=True),
    sa.Column('signature1_image_url', sa.String(length=500), nullable=True),
    sa.Column('signature2_name', sa.String(length=100), nullable=True),
    sa.Column('signature2_title', sa.String(length=100), nullable=True),
    sa.Column('signature2_image_url', sa.String(length=500), nullable=True),
    sa.Column('certificate_template', sa.String(length=50), nullable=True),
    sa.Column('certificate_config_updated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('participants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('organization', sa.String(length=200), nullable=True),
    sa.Column('designation', sa.String(length=100), nullable=True),
    sa.Column('linkedin_url', sa.String(length=300), nullable=True),
    sa.Column('ticket_id', sa.String(length=20), nullable=False),
    sa.Column('email_sent', sa.Boolean(), nullable=True),
    sa.Column('certificate_generated', sa.Boolean(), nullable=True),
    sa.Column('registered_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticket_id')
    )
    op.create_table('quizzes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('timer_per_question', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('certificates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('participant_id', sa.Integer(), nullable=False),
    sa.Column('certificate_number', sa.String(length=50), nullable=False),
    sa.Column('issued_date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('certificate_type', sa.String(length=50), nullable=True),
    sa.Column('organizer_name', sa.String(length=200), nullable=True),
    sa.Column('organizer_logo_url', sa.String(length=500), nullable=True),
    sa.Column('sponsor_name', sa.String(length=200), nullable=True),
    sa.Column('sponsor_logo_url', sa.String(length=500), nullable=True),
    sa.Column('event_location', sa.String(length=300), nullable=True),
    sa.Column('event_theme', sa.String(length=300), nullable=True),
    sa.Column('signature1_name', sa.String(length=100), nullable=True),
    sa.Column('signature1_title', sa.String(length=100), nullable=True),
    sa.Column('signature1_image_url', sa.String(length=500), nullable=True),
    sa.Column('signature2_name', sa.String(length=100), nullable=True),
    sa.Column('signature2_title', sa.String(length=100), nullable=True),
    sa.Column('signature2_image_url', sa.String(length=500), nullable=True),
    sa.Column('email_sent', sa.Boolean(), nullable=True),
    sa.Column('email_sent_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['participant_id'], ['participants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('certificate_number')
    )
    op.create_table('quiz_participants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quiz_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('total_time', sa.Integer(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['quiz_id'], ['quizzes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quiz_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quiz_id', sa.Integer(), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('options', sa.Text(), nullable=False),
    sa.Column('correct_answer', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['quiz_id'], ['quizzes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quiz_answers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('participant_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('answer', sa.String(length=200), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=True),
    sa.Column('time_taken', sa.Integer(), nullable=True),
    sa.Column('answered_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['participant_id'], ['quiz_participants.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['quiz_questions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('quiz_answers')
    op.drop_table('quiz_questions')
    op.drop_table('quiz_participants')
    op.drop_table('certificates')
    op.drop_table('quizzes')
    op.drop_table('participants')
    op.drop_table('events')
    # ### end Alembic commands ###
